username = 'yannick.matimbe'
password = 'Y@nnick2003'
login_url = 'https://fenix.isutc.ac.mz/cas/login?service=https://fenix.isutc.ac.mz/isutc/'
logged_url = 'https://fenix.isutc.ac.mz/isutc/fenixEduIndex.do'
mark_url = 'https://fenix.isutc.ac.mz/isutc/publico/executionCourse.do?method=marks&executionCourseID=1126312223704031'
